---
- name: read yml
  shell: 'cat /etc/unbound/conf.d/00-cluster.conf | grep \.local-data-ptr | sed "s/\"/ /g" | cut -d ":" -f2- | cut -d " " -f 4'
  register: local_hosts
  become: yes
  become_user: root

- name: get all_hosts
  set_fact:
    all_hosts: "{{ local_hosts.stdout_lines | list }}"

- name: set all hosts
  add_host:
    host: {{ item }}
    groups:
      - RANGER_ADMIN
      - KAFKA_BROKER
      - NAMENODE
      - KNOX_GATEWAY
      - RESOURCEMANAGER
      - ZOOKEEPER_SERVER
      - HISTORYSERVER
      - ATLAS_SERVER
      - HBASE_MASTER
  with_itmes: "{{ all_hosts }}"