---
- name: read yml
  shell: 'cat /etc/unbound/conf.d/00-cluster.conf | grep \.local-data-ptr | sed "s/\"/ /g" | cut -d ":" -f2- | cut -d " " -f 4'
  register: local_hosts
  become: yes
  become_user: root

- name: get all_hosts
  set_fact:
    all_hosts: "{{ local_hosts.stdout_lines | list }}"

- name: Invoke wire encryption for atlas
  include_role:
    name: certs
  vars:
    component_prefix: atlas
  become: yes
  become_user: root

- name: Invoke wire encryption for ranger plugins
  include_role:
    name: certs
  vars:
    component_prefix: ranger-atlas-plugin
    certs_local_alias: "rangerAtlasAgent"
    certs_jks_file: ranger-plugin.jks
    certs_jks_req: ranger-plugin.req
    certs_jks_cert: ranger-plugin.crt
  become: yes
  become_user: root
  when: install_ranger == true

- name: copy password_gen
  template:
    src: password_gen.j2
    dest: /etc/atlas/conf/password_gen
    mode: 755
  become: yes
  become_user: root

- name: Execute the script
  command: sh /etc/atlas/conf/password_gen
  become: yes
  become_user: root

- name: Set right permission for atlas jceks files
  file:
    path: "{{ item }}"
    mode: 444
    owner: atlas
    group: hadoop
  loop:
    - "{{ passwdFileLocationActualPath }}"
    - "{{ passwdCrcFileLocation }}"

- name: Save SSL configs for Atlas
  include_role:
    name: ambari_configure_service
  vars:
    ambari_component_section_name: "{{ atlas_application-properties_config_type }}"
    ambari_component_props: "{{ atlas_application-properties_config_props }}"

- name: Save SSL configs for Atlas-Ranger Plugin
  include_role:
    name: ambari_configure_service
  vars:
    ambari_component_section_name: "{{ atlas_ranger_plugin_config_type }}"
    ambari_component_props: "{{ atlas_ranger_plugin_config_props }}"