---
- hosts: localhost
  tasks:
   - name: get all_hosts
     set_fact:
       all_hosts: "{{ /etc/unbound/conf.d/00-cluster.conf | get_all_hosts }}"

   - name: set all hosts
     add_host:
       host: "{{ item }}"
       groups:
         - RANGER_ADMIN
         - KAFKA_BROKER
         - NAMENODE
         - KNOX_GATEWAY
         - RESOURCEMANAGER
         - ZOOKEEPER_SERVER
         - HISTORYSERVER
         - ATLAS_SERVER
         - HBASE_MASTER
     with_items: "{{ all_hosts }}"