- name: Get ambari java home
  delegate_to: localhost
  run_once: true
  set_fact:
    java_home: '{{ "/etc/ambari-server/conf/ambari.properties" | get_ambari_java_home }}'

- name: set CA cert path and all hosts
  set_fact:
    ca_cert_path: "{{ java_home }}/jre/lib/security/cacerts"
    all_hosts: '{{ "/etc/unbound/conf.d/00-cluster.conf" | get_all_hosts }}'

- name: Include common certs
  include_tasks: setup_basic_certs.yaml

- name: import the certificate to truststore
  become: true
  command: >
    keytool -import
      -noprompt
      -alias "{{ ansible_fqdn }}"
      -file "{{ server_certs_dir }}/{{ cert_pub_key }}"
      -keystore "{{ all_jks_file }}"
      -storepass "{{ certs_jks_store_password }}"
  args:
    chdir: "{{ client_certs_dir }}"
    creates: "{{ all_jks_file }}"

- name: copy all.jks to all hosts
  become: true
  delegate_to: "{{ item }}"
  copy:
    src: "{{ client_certs_dir }}/{{ all_jks_file }}"
    dest: "{{ client_certs_dir }}/"
  with_items: "{{ all_hosts }}"
  when: item != "{{ ansible_fqdn }}"

- name: Import certs in all hosts common certs
  include_tasks: distribute_all_certs.yaml



- name: import the certificate to truststore
  become: true
  delegate_to: "{{ item }}"
  command: >
    keytool -import
      -noprompt
      -alias "{{ ansible_fqdn }}"
      -file "{{ server_certs_dir }}/{{ cert_pub_key }}"
      -keystore "{{ all_jks_file }}"
      -storepass "{{ certs_jks_store_password }}"
  args:
    chdir: "{{ client_certs_dir }}"
    creates: "{{ all_jks_file }}"
  with_items: "{{ all_hosts }}"
  when: item != "{{ ansible_fqdn }}"
