certs_use_local_ca: true
knox_protocol: https
knox_port: 8443
domain: knoxexample.com
webserver_service: httpd

knox_ca_cert_dir: /usr/local/apache2/ssl
certs_dir: /etc/wire_encryption/knox
knox_ssl_key: loadbalancer.key
knox_ssl_csr: loadbalancer.csr
knox_ssl_cert: loadbalancer.cert